export const Categories = [
    "Agreements",
    "Mortgage",
    "Busines Plans",
    "Car",
    "Constructions",
    "Education",
    "Employment",
    "Family",
    "Financial",
    "Customer success",
    "Forms",
    "Tax From templates",
    "Healthcare",
    "Invocies",
    "Legal",
    "Manufacturing",
    "Marketing",
    "Proposals",
    "Real estate",
    "Sales",
    "Contracts",
    "Technology",
    "Software",
    "Consluting",
];