const Social = [
  {
    className: "OnlyOffice",
    title: "OnlyOffice",
    target: "_blank",
    rel: "",
    src: "/images/social-icons/mail.react.svg",
    size: "24px",
    filter: true,
  },
  {
    href: "https://www.facebook.com/pages/OnlyOffice/833032526736775",
    className: "faceBook",
    title: "Facebook",
    target: "_blank",
    rel: "",
    src: "/images/social-icons/facebook.react.svg",
    size: "24px",
    filter: true,
  },
  {
    href: "https://twitter.com/ONLY_OFFICE",
    className: "twitter",
    title: "Twitter",
    target: "_blank",
    rel: "nofollow",
    src: "/images/social-icons/twitter.react.svg",
    size: "24px",
    filter: true,
  },
  {
    href: "https://www.linkedin.com/groups/6726380/",
    className: "linkedin",
    title: "LinkedIn",
    target: "_blank",
    rel: "nofollow",
    src: "/images/social-icons/linkedin.react.svg",
    size: "24px",
    filter: true,
  },
  {
    href: "https://www.youtube.com/user/onlyofficeTV",
    className: "youTube",
    title: "YouTube",
    target: "_blank",
    rel: "nofollow",
    src: "/images/social-icons/youtube.react.svg",
    size: "24px",
    filter: true,
  },
  {
    href: "https://www.onlyoffice.com/blog",
    className: "blog",
    title: "Blog",
    target: "_blank",
    rel: "",
    src: "/images/social-icons/wordpress.react.svg",
    size: "24px",
    filter: true,
  },
  {
    href: "https://medium.com/onlyoffice",
    className: "medium",
    title: "Medium",
    target: "_blank",
    rel: "",
    src: "/images/social-icons/medium.react.svg",
    size: "24px",
    filter: true,
  },
  {
    href: "https://www.instagram.com/the_onlyoffice/",
    className: "instagram",
    title: "Instagram",
    target: "_blank",
    rel: "",
    src: "/images/social-icons/instagram.react.svg",
    size: "24px",
    filter: true,
  },
  {
    href: "https://github.com/ONLYOFFICE/",
    className: "github",
    title: "GitHub",
    target: "_blank",
    rel: "",
    src: "/images/social-icons/github.react.svg",
    size: "24px",
    filter: true,
  },
  {
    href: "https://fosstodon.org/@ONLYOFFICE",
    className: "fosstodon",
    title: "Fosstodon",
    target: "_blank",
    rel: "",
    src: "/images/social-icons/fosstodon.react.svg",
    size: "24px",
    filter: true,
  },
];

export default Social;
