import { chromium } from "playwright";
import { pathToFileURL } from "node:url";
import { join } from "node:path";
const url = pathToFileURL(join(process.cwd(), "dist", "index.html")).href;
const pageErrors = [], consoleErrors = [];
const browser = await chromium.launch();
const page = await browser.newPage();
page.on("pageerror", e => pageErrors.push(String(e)));
page.on("console", m => { if (m.type()==="error" && !/Failed to load resource/i.test(m.text())) consoleErrors.push(m.text()); });
console.log("Opening (no server):", url);
await page.goto(url, { waitUntil: "load", timeout: 20000 });
await page.waitForFunction(() => (document.getElementById("oforms-root")?.children.length ?? 0) > 0, { timeout: 10000 });
const h1 = (await page.locator("#oforms-root h1").first().textContent())?.trim();
const cards = await page.locator("#oforms-root a").count();
const boxes = await page.locator('#oforms-root input[type=checkbox]').count();
console.log(`H1: "${h1}"`);
console.log(`cards: ${cards}, filters: ${boxes}`);
await page.locator('#oforms-root input[type=checkbox]').first().click({force:true});
await page.waitForTimeout(500);
const after = await page.locator("#oforms-root a").count();
console.log(`after filter click: ${after} cards`);
if (pageErrors.length) console.log("PAGE ERRORS:", pageErrors.slice(0,3));
if (consoleErrors.length) console.log("CONSOLE ERRORS:", consoleErrors.slice(0,3));
await browser.close();
const ok = h1 && cards>0 && boxes>0 && pageErrors.length===0;
console.log(ok ? "\nFILE:// PASS (no server)" : "\nFILE:// FAIL");
process.exit(ok?0:1);
